name: cleanup caches on master
on:
  workflow_dispatch:
    
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:      
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          echo "Fetching list of cache key"
          x=$(gh actions-cache list -R $REPO -B $BRANCH | wc -l)
          if (($x > 5));then
              y=$((x-5))
              cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH -L $y --order asc --sort last-used | cut -f 1 )
              ## Setting this to not fail the workflow while deleting cache keys. 
              set +e
              echo "Deleting caches..."
              for cacheKey in $cacheKeysForPR
              do
                  echo "Fetching list of cache key $cacheKey"
                  gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
              done
          fi
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: master
