# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch: 
    inputs:
      name:
        type: boolean
        description: build native
      native:
        required: true
 

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Set up Graal VM 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17' # for a specific JDK 17; or '17' for the latest JDK 17
        distribution: 'graalvm' # New 'distribution' option
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build native binary
      if: github.event.inputs.native
      run: mvn -B package -Dmaven.test.skip=true -Pnative --file pom.xml  
    - name: list artefact
      run: ls -ltr vintage-store/target
    - name: store artefacts
      run: mkdir dist && cp vintage-store/target/*.jar dist
    - name: store native artefacts
      if: github.event.inputs.native
      run: cp vintage-store/target/*runner dist  
    - uses: actions/upload-artifact@v3
      with:
            name: vintage-store
            path: dist  
        

    
